### ISSUE TITLE
week3-Task10

### ISSUE THREAD

**Issue by KHajili98** [nijatjafarov/PragmatechCsharpPoroject#2]
taski basqa yanasma ile yoxlayarsan. Ve sonda niye vurma cedvel bura yazmisan ki?

**Comment by nijatjafarov** [comment]
Yaxşı. Orada yalnışlıq olub, özüm üçün test məqsədilə yazmışdım, diqqətsizlik edib düzəlişlər etmədən repoya push etmişəm
