### ISSUE TITLE
week 3 - task 11

### ISSUE THREAD

**Issue by KHajili98** [nijatjafarov/PragmatechCsharpPoroject#3]
internetden birebir kopyaya benzeyir )))
[https://www.c-sharpcorner.com/code/3759/how-to-find-prime-numbers-from-1-to-100-using-c-sharp.aspx](url)

**Comment by nijatjafarov** [comment]
Sözün düzü issue-nu görəndə təəccübləndim, belə bir iddihamla qarşılaşacağımı gözləmirdim. Təbrik edirəm, məndən fərqli olaraq internetdə bu problemin hazır həllərinə baxmısınız, hətta mənimkinin bənzərini tapacaq dərəcədə

**Comment by KHajili98** [comment]
Tebrikin ucun derin tesekkurlerimi bildirirem :) ...
Teki senin yazdiginin benzeri internetde olsun. Sen kopyalama esas budur meqsedimiz, bele hal olanda bildirib qarwisini almaqdir.
